version: "3"
services:
  api:
    build: .
    ports:
      - 3000:3000
    command: flask run --host=0.0.0.0 --port=3000 --reload --debugger
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:root@db:5433/insta_clone
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    container_name: api
    restart: unless-stopped
    networks:
      - insta_clone
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - 5432:5433
    environment:
      - POSTGRES_DB=insta_clone
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    container_name: postgres
    restart: unless-stopped
    networks:
      - insta_clone
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: unless-stopped
    networks:
      - insta_clone

  celery_worker:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:root@db:5433/insta_clone
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0q
    container_name: celery_worker
    restart: unless-stopped
    networks:
      - insta_clone
    depends_on:
      - db
      - redis
    command: celery -A src.app.celery_app worker --loglevel=info

networks:
  insta_clone:

volumes:
  pgdata:
